### ISSUE TITLE
Wrong behavior when access_token/refresh_token has unusual symbols

### ISSUE THREAD

**Issue by chetverikov** [catberry/catberry-oauth2-client#1]
If refresh_token or access_token contain characters other than numbers and letters, this can lead to infinite loop applications.

An example of a token:  `mYGnZR5RfI0XvpJoEyqzii+SFPW3hoObEoKn/xVQWz0=`

> generator: crypto.randomBytes(32).toString('base64')    //nodejs

The data token may not be correctly parsed from cookie here https://github.com/catberry/catberry-oauth2-client/blob/c07ef6416396f957be5f4bfb59a8829279215cca/lib/helpers/cookieHelper.js#L45-L55
This problem is resolved modified code:

``` javascript
  getFromRequest: function(request) {
    if (!request.headers || typeof(request.headers.cookie) !== 'string') {
      return {};
    }

    var result = {};
    request.headers.cookie
      .split(';')
      .forEach(function(cookieString) {
        cookieString = cookieString.trim();

        var separatorIndex = cookieString.indexOf('=');

        result[cookieString.substr(0, separatorIndex)] = cookieString.substr(separatorIndex + 1);
      });

    return result;
  }
```

If you correct the problem with cookies, then there is a problem with sending. For example, the query refresh_token:

``` javascript
{
  "refresh_token": "mYGnZR5RfI0XvpJoEyqzii+SFPW3hoObEoKn/xVQWz0=",
  "grant_type": "refresh_token"
}

// on server req.body will contain

{
  "refresh_token": "mYGnZR5RfI0XvpJoEyqzii SFPW3hoObEoKn/xVQWz0=", // plus changed to space
  "grant_type": "refresh_token"
}

```

**Comment by rdner** [comment]
The second problem with `+` POST sending is fixed by this release https://github.com/catberry/catberry-uhr/releases/tag/4.0.2

**Comment by rdner** [comment]
Fixed in https://github.com/catberry/catberry-oauth2-client/releases/tag/2.0.6
