### ISSUE TITLE
Refreshing data each minute, Destroying auth data.

### ISSUE THREAD

**Issue by vaseker** [catberry/catberry-oauth2-client#3]
Привет!
1. ~~Это норма, что клиент, авторизованный через `"grantType": "password"`, ходит в oauth-бэкенд каждую минуту?~~ Нормально, что oauth-клиент трижды ходит в oauth-сервер по истечении времени жизни токена? Трижды, видимо, потому, что хранилище с авторизацией привязано к 3м компонентам.
   [Пример](https://github.com/vaseker/netbuyer/blob/master/catberry_stores/User.js#L51)
2. И второй вопрос: возможно ли затереть куки авторизации, что указаны в конфиге клиента, через сам клиент? Предусмотрены ли соответсвующие endpoints? Хотя, кажется, что разавторизация должна проходить через oauth-сервер, чтобы загасить ненужные токены...

Спасибо!

**Comment by rdner** [comment]
1.Если я тебея правильно понял, это нормально, потому что:
- он пытается обновить токен через refreshToken, 
- затем если не получилось редиректит на URL, где удаляет куки с токеном
- потом редиректит на URL который выставляет новый client credential token

С привязками к компонентам это не может быть связано, потому что когда множество компонентов несколько раз подряд спрашивают один и тот же `this.$context.getStoreData()`, запрос проскакивает только первый, остальные становятся в очередь ожидая того же ответа от сервера
1. Есть метод `ResourceServer.prototype.removeAuthorization = function (context) { }`
   Чем он не подошел?

**Comment by vaseker** [comment]
Непонятно, почему рефреш токена происходит 3 раза, и все успешно: запросы
идут в один и тот же url, ответы 200.

ResourceServer.prototype.removeAuthorization тупо не заметил в доке) Это
то, что нужно)
1. Если я тебея правильно понял, это нормально, потому что:
2. он пытается обновить токен через refreshToken,
3. затем если не получилось редиректит на URL, где удаляет куки с токеном
4. потом редиректит на URL который выставляет новый client credential
   token

С привязками к компонентам это не может быть связано, потому когда
множество компонентов несколько раз подряд спрашивают один и тот же
this.$context.getStoreData(), запрос проскакивает только первый, остальные
становятся в очередь ожидая того же результата
1. Есть метод ResourceServer.prototype.removeAuthorization = function
   (context) { } Чем он не подошел?

**Comment by rdner** [comment]
> Непонятно, почему рефреш токена происходит 3 раза, и все успешно: запросы
> идут в один и тот же url, ответы 200.

А URL то какой? Методы отличаются? Нужны логи запросов, хотя бы скрин, на котором все видно. URL, заголовки, ответ.

**Comment by vaseker** [comment]
url один и тот же /api/v0/user/ , метод GET.

[скрин](https://yadi.sk/i/L8McPgkjhSt5u)
Справа лог сервера:
сначала развернутый request,
потом аргументы res.end()
и в конце обычный завершающий лог от `morgan`

catberry как-то странно видит `Incoming request`: ко времени снятия скриншота, сайт не был открыт в браузере около 10 минут, и отсюда неясно, откуда catberry ловит входящие (причем сразу 3 на один момент времени). как-то живет сам-по себе.

время жизни oauth токенов - 14дней. время жизни авторизационных кук - сотни лет.

**Comment by rdner** [comment]
> catberry как-то странно видит Incoming request: ко времени снятия скриншота, сайт не был открыт в браузере около 10 минут, и отсюда неясно, откуда catberry ловит входящие (причем сразу 3 на один момент времени). как-то живет сам-по себе.

Это невозможно, потому что на сервере само ничего не происходит, только по запросу пользователя, я бы проверил систему на наличие демонов, которые делают запросы на этот порт, может быть отсюда и все проблемы. 

Я сначала подумал что речь про обновление токена, но тут совсем другая проблема, у тебя просто что-то в системе постоянно загружает страницу с сервера, от этого запросы за объектом пользователя.

**Comment by vaseker** [comment]
Окей. Проверю систему и подниму проект в вакууме.

**Comment by vaseker** [comment]
Действительно, в системе сидела какая-то дрянь, спамящая в порт.
